### ISSUE TITLE
2.13.2 - Segmentation Fault - Ubuntu 24.02

### ISSUE THREAD

**Issue by ClementLeBihan** [CloudCompare/CloudCompare#2033]
Hi, 

This pcd file is loaded with CloudCompare x2.13.2 but when I click on it on the left panel, CloudCompare segfault. 

Do you know this issue ? 

Here is the gbd result : 

```
#0  0x00007ffff3dfef38 in QIODevice::isOpen() const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff5da1c34 in ccHObject::fromFileNoChildren (this=0x5555579855e0, in=..., dataVersion=4902, flags=-420779691, oldToNewIDMap=...)
    at /home/clebihan/ExternalSoftwares/CloudCompare/libs/qCC_db/src/ccHObject.cpp:1151
#2  0x00007ffff5da1398 in ccHObject::fromFile (this=0x5555579855e0, in=..., dataVersion=4902, flags=-420779691, oldToNewIDMap=...)
    at /home/clebihan/ExternalSoftwares/CloudCompare/libs/qCC_db/src/ccHObject.cpp:1027
#3  0x00007fffe6eb656c in GetSelectedViewPorts(std::vector<ccHObject*, std::allocator<ccHObject*> > const&) () at /usr/local/lib/cloudcompare/plugins/libQANIMATION_PLUGIN.so
#4  0x00007fffe6eb675a in qAnimation::onNewSelection(std::vector<ccHObject*, std::allocator<ccHObject*> > const&) () at /usr/local/lib/cloudcompare/plugins/libQANIMATION_PLUGIN.so
#5  0x000055555594e384 in ccPluginUIManager::handleSelectionChanged (this=0x55555672c870) at /home/clebihan/ExternalSoftwares/CloudCompare/qCC/pluginManager/ccPluginUIManager.cpp:287
#6  0x00005555558c4d96 in MainWindow::enableUIItems (this=0x555555c92180, selInfo=...) at /home/clebihan/ExternalSoftwares/CloudCompare/qCC/mainwindow.cpp:11329
#7  0x00005555558c3491 in MainWindow::updateUIWithSelection (this=0x555555c92180) at /home/clebihan/ExternalSoftwares/CloudCompare/qCC/mainwindow.cpp:11100
#8  0x000055555590da90 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (MainWindow::*)()>::call(void (MainWindow::*)(), MainWindow*, void**)
    (f=(void (MainWindow::*)(MainWindow * const)) 0x5555558c33ec <MainWindow::updateUIWithSelection()>, o=0x555555c92180, arg=0x55555763f248) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#9  0x000055555590a86a in QtPrivate::FunctionPointer<void (MainWindow::*)()>::call<QtPrivate::List<>, void>(void (MainWindow::*)(), MainWindow*, void**)
    (f=(void (MainWindow::*)(MainWindow * const)) 0x5555558c33ec <MainWindow::updateUIWithSelection()>, o=0x555555c92180, arg=0x55555763f248) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
```

Here is the file (extract it to get pcd, I couldn't upload pcd file). 
[000000.zip](https://github.com/user-attachments/files/16173977/000000.zip)

**Comment by dgirardeau** [comment]
Hi,

I can't reproduce this issue on Windows... Maybe someone can on Linux? @rjanvier maybe?

**Comment by ClementLeBihan** [comment]
In fact It segfault even if I open a .ply, so it is not relative to this specific file :/

**Comment by ClementLeBihan** [comment]
Arf in fact even the 2.12.4 has the same problem. It worked well when I was on 22.04 but changed yesterday to 24.02. Have you already try CloudCompare in 24.02 ?

**Comment by ClementLeBihan** [comment]
In fact it seems that the bug cames from a mix of 2.12 libs and 2.13 libs installed on my computer. Removed everything, re-compile and everything works fine !
Sorry for the disturb !
